apiVersion: v1
data:
  SPOTIPY_CLIENT_ID: "secret ID here"
  SPOTIPY_CLIENT_SECRET: "Secret pass here"
kind: Secret
metadata:
  name: spotify-secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trendz
  template:
    metadata:
      labels:
        app: trendz
    spec:
      containers:
        - name: trendz-container
          image: pshar10/trendz:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: spotify-secrets-volume
              mountPath: /app/secrets  
              readOnly: true
      volumes:
        - name: spotify-secrets-volume
          secret:
            secretName: spotify-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: trendz-service
  namespace: default
spec:
  selector:
    app: trendz
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5000 
      nodePort: 30195
  type: NodePort  

